# Generated by Django 3.1.7 on 2021-03-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_trade_trade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(default='BUY', max_length=64),
            preserve_default=False,
        ),
    ]
